dataset:
  name: 'cancer'  # iris, wine, 'cancer', 'drug'
  target_col: 'target'
  seed: 42
  test_size: 0.2
  val_size: 0.25

knn:
  k_range: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

loo:
  k_range: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

visualization:
  save_plots: true
  plots_dir: 'plots'


